---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetime-scaler-clusterrole
rules:
- apiGroups:
  - downscaler.go
  resources:
  - downscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - downscaler.go
  resources:
  - downscalers/finalizers
  verbs:
  - update

- apiGroups:
  - downscaler.go
  resources:
  - downscalers/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - statefulsets
  verbs:
  - get
  - patch
  - list
  - watch

- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - patch
  - list
  - watch